### ISSUE TITLE
input.json caching too aggressive

### ISSUE THREAD

**Issue by ademets** [HeliosOrg/SimpleDataIntegration#1]
I am unable to update the `server_url` value in the `input.json` file, once Unreal Engine starts up with the plug in enabled. Neither restarting Unreal Engine Editor, nor a full rebuild of the project under Visual Studio helps. There seems to be some caching going on, that is not updating the `server_url` value, once set.

**Comment by derindutz** [comment]
Hey! In the plugin's current state, if you update `server_url` in the `input.json` file, we don't go through nodes you've previously created to update them. This means that unfortunately you will have to remove nodes you created before you updated `server_url` and re-create them. 

If you're interested in the technical details, we update the server url in the node's [GetMenuActions function](https://github.com/HeliosOrg/SimpleDataIntegrationPlugin/blob/db1a6aa2dca50d9d2e1b7b36840b8278f22d71cf/Source/Private/K2Node_Helios.cpp#L80), which is called every time you attempt to place a Blueprint node. UE4 does indeed do some caching, so if you update `server_url` in the `input.json` file, you will need to close the UE4 program and restart it for the server url to be updated in all subsequently placed nodes. Nodes maintain their own state so any nodes you placed previously will still send requests to the old server url and therefore they need to be replaced. 

Hope that helps!
